### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TimothyGu** [uclaacm/learning-lab-crash-course-su20#1]
Hi,

Thanks for open-sourcing these notes! It's great to see what you all are up to.

I saw that the whole repo is under the MIT license. That's great, but as you probably know, the MIT license primarily deals with software ("this software and associated documentation files"). You might want to look into the [Creative Commons Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) license, which is more appropriate for creative works (like this one), is in the same family of licenses as the one used for Wikipedia/Wikibooks/Wiktionary/etc., and is similar in spirit to MIT.

You could also use separate licensing for text and software, similar to [Google](https://web.dev/):

> Except as otherwise noted, the content of this page is licensed under the Creative Commons Attribution 4.0 License, and code samples are licensed under the Apache 2.0 License.

Feel free to choose any of these and/or close this issue any time. This is just a tip in case you all are not aware of the CC licenses.

**Comment by malsf21** [comment]
Hey Tim, thanks for pointing this out - it totally slipped my mind! I'll review the CC BY 4.0 and likely merge it + update our README. Appreciate it ❤️ !

**Comment by malsf21** [comment]
Resolved this in the commit https://github.com/uclaacm/learning-lab-crash-course-su20/commit/9b94188081315600024ddbd8d2eaf3d82bb96421 (been a bit lazy with git in this repo, probably for the worse). Thanks again for the contribution!
